server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/evil1/IdeaProjects/WorkProcessLog/config-server/src/main/resources/config